### ISSUE TITLE
Site Visit - Mentor Questions

### ISSUE THREAD

**Issue by carriepetti** [CHS-WBL-2022/WBL22-Company#1]
This issue will be used to keep track of all questions we have for our Mentors during our Virtual Site Visit.

**Comment by IsaiahBobola** [comment]
What led you to this field? 
What surprised you about this field?
How has your job evolved? Changed?

**Comment by AndewAP** [comment]
1. What is your favorite aspect of your job?
2. Do you think your field of work is expanding or decreasing?
3. How do you feel about the state of your job right now?
